CLIENT_IP = 'localhost'
CLIENT_PORT = 20000
SERVER_IP = 'localhost'
SERVER_PORT = 30000
HEADER_SIZE = 10
PAYLOAD_SIZE = 1008
SEGMENT_SIZE = HEADER_SIZE + PAYLOAD_SIZE

# Flags
NONE = 0
ACK = 1
SYN = 2
SYNACK = 3
FIN = 4
FINACK = 5

TIMEOUT = 1
MAX_ATTEMPTS = 3